from models.department import Department
from models.diagnose import Diagnose
from models.mkb import Mkb
from models.sample import Sample
from models.patient_diagnose import PatientDiagnose
from models.patient import Patient
from models.sample_result import SampleResult
from models.test import Test
from models.user import User
